project:
    edition: '@project.version@'

server:
    port: 8080
    session-timeout: 60
    
spring:
    profiles:
        active: '@profiles.active@'
        
mybatis:
    mapper-locations: classpath:/mapper/*Mapper.xml